#!/usr/bin/env python2

import sys
from argparse import ArgumentParser

sys.path.append('./lib')

from uas_emulator.uas_manager import UASManager

def main():
	parser = ArgumentParser(description=__doc__)

	# Emulator Arguments
	parser.add_argument("--name", help="UAS system name", default="uas")
	parser.add_argument("--rate", help="Rate that the system check for updates, tune down on slower machines", default=100)

	# Mavlink Arguments
	parser.add_argument("--device", help="Input device to use", default="udp:localhost:14550")
	parser.add_argument("--baudrate", type=int,
					    help="Baud rate to use if a serial device is specified", default=115200)
	parser.add_argument("--sysid", type=int, help="Emulated UAS System ID", default=1)
	parser.add_argument("--compid", type=int, help="Emulated UAS Component ID", default=1)

	args = parser.parse_args()

	uas = UASManager(args)
	uas.run()

if __name__ == "__main__":
	main()

