#!/usr/bin/env python2

import sys

sys.path.append('./lib')

from uas_emulator.uas_manager import UASManager
from uas_emulator.timer import UpdateTimer

def main():
	uas_name = "uas"
	update_rate = 100 #Hz

	uas = UASManager(uas_name)
	timer = UpdateTimer(uas_name, update_rate, uas.update)

	while True:
		try:
			timer.run()
		except KeyboardInterrupt:
			uas.shutdown()
			exit()

if __name__ == "__main__":
	main()

